# Generated by Django 3.2.8 on 2021-11-06 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211106_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
